INSERT INTO content (key, language, value, published) VALUES
('home.title', 'sr', '"Dobrodošli u Apartmane Jovča"'::jsonb, true),
('home.description', 'sr', '"Uživajte u udobnom smeštaju u prelepom okruženju."'::jsonb, true),
('home.subtitle', 'sr', '"Vaš savršeni odmor u srcu prirode"'::jsonb, true),
('home.hero.title', 'sr', '"Doživite udobnost i prirodu"'::jsonb, true),
('home.hero.subtitle', 'sr', '"Rezervišite svoj boravak u modernim apartmanima"'::jsonb, true),
('home.hero.cta', 'sr', '"Rezerviši"'::jsonb, true),
('home.features.title', 'sr', '"Naše prednosti"'::jsonb, true),
('home.features.amenities', 'sr', '"Moderno opremljeni apartmani"'::jsonb, true),
('home.features.location', 'sr', '"Odlična lokacija u blizini atrakcija"'::jsonb, true),
('home.features.parking', 'sr', '"Besplatan parking"'::jsonb, true),
('home.features.wifi', 'sr', '"Besplatan WiFi"'::jsonb, true),
('home.features.breakfast', 'sr', '"Dostupan doručak"'::jsonb, true),
('home.features.petFriendly', 'sr', '"Dozvoljeni ljubimci"'::jsonb, true),
('home.contact.title', 'sr', '"Kontaktirajte nas"'::jsonb, true),
('home.contact.available', 'sr', '"Dostupni smo 24/7 za sve vaše potrebe."'::jsonb, true),
('home.testimonials.title', 'sr', '"Šta kažu naši gosti"'::jsonb, true),
('home.testimonials.readMore', 'sr', '"Pročitaj više recenzija"'::jsonb, true),
('apartments.title', 'sr', '"Naši apartmani"'::jsonb, true),
('apartments.description', 'sr', '"Pronađite savršen smeštaj"'::jsonb, true),
('apartments.amenities', 'sr', '"Sadržaji"'::jsonb, true),
('apartments.size', 'sr', '"Veličina"'::jsonb, true),
('apartments.beds', 'sr', '"Kreveti"'::jsonb, true),
('apartments.capacity', 'sr', '"Kapacitet"'::jsonb, true),
('apartments.viewDetails', 'sr', '"Vidi detalje"'::jsonb, true),
('apartments.bookNow', 'sr', '"Rezerviši"'::jsonb, true),
('apartments.noApartments.title', 'sr', '"Nema dostupnih apartmana"'::jsonb, true),
('apartments.noApartments.message', 'sr', '"Proverite kasnije ili nas kontaktirajte za dostupnost."'::jsonb, true),
('attractions.title', 'sr', '"Lokalne atrakcije"'::jsonb, true),
('attractions.description', 'sr', '"Otkrijte lepotu okolnog područja"'::jsonb, true),
('attractions.readMore', 'sr', '"Pročitaj više"'::jsonb, true),
('attractions.noAttractions.title', 'sr', '"Nema navedenih atrakcija"'::jsonb, true),
('attractions.noAttractions.message', 'sr', '"Proverite kasnije za ažuriranja o lokalnim atrakcijama."'::jsonb, true),
('location.title', 'sr', '"Lokacija"'::jsonb, true),
('location.description', 'sr', '"Kako do nas"'::jsonb, true),
('location.address', 'sr', '"Adresa"'::jsonb, true),
('location.directions', 'sr', '"Uputstva za dolazak"'::jsonb, true),
('location.nearby', 'sr', '"Obližnje atrakcije"'::jsonb, true),
('prices.title', 'sr', '"Cene i Smještaj"'::jsonb, true),
('prices.description', 'sr', '"Transparentne cene bez skrivenih troškova"'::jsonb, true),
('prices.bed', 'sr', '"Tip kreveta"'::jsonb, true),
('prices.capacity', 'sr', '"Kapacitet"'::jsonb, true),
('prices.included', 'sr', '"U cenu je uključeno:"'::jsonb, true),
('prices.perNight', 'sr', '"po noćenju"'::jsonb, true),
('prices.totalPrice', 'sr', '"Ukupna cena"'::jsonb, true),
('prices.selectDates', 'sr', '"Izaberite datume da vidite cene"'::jsonb, true),
('prices.noPrices.title', 'sr', '"Trenutno nema dostupnih cena"'::jsonb, true),
('prices.noPrices.message', 'sr', '"Molimo proverite kasnije ili nas kontaktirajte za više informacija."'::jsonb, true),
('prices.errors.loadFailed', 'sr', '"Greška pri učitavanju cena. Molimo pokušajte ponovo kasnije."'::jsonb, true),
('contact.title', 'sr', '"Kontaktirajte nas"'::jsonb, true),
('contact.description', 'sr', '"Rado ćemo vam odgovoriti"'::jsonb, true),
('contact.form.name', 'sr', '"Vaše ime"'::jsonb, true),
('contact.form.email', 'sr', '"Email adresa"'::jsonb, true),
('contact.form.phone', 'sr', '"Broj telefona"'::jsonb, true),
('contact.form.message', 'sr', '"Vaša poruka"'::jsonb, true),
('contact.form.submit', 'sr', '"Pošalji poruku"'::jsonb, true),
('contact.form.success', 'sr', '"Poruka uspešno poslata! Javićemo vam se uskoro."'::jsonb, true),
('contact.form.error', 'sr', '"Greška pri slanju poruke. Molimo pokušajte ponovo."'::jsonb, true),
('contact.info.title', 'sr', '"Kontakt informacije"'::jsonb, true),
('contact.info.address', 'sr', '"Adresa"'::jsonb, true),
('contact.info.phone', 'sr', '"Telefon"'::jsonb, true),
('contact.info.email', 'sr', '"Email"'::jsonb, true),
('contact.info.whatsapp', 'sr', '"WhatsApp"'::jsonb, true),
('contact.hours.title', 'sr', '"Radno vreme"'::jsonb, true),
('contact.hours.weekdays', 'sr', '"Ponedeljak - Petak"'::jsonb, true),
('contact.hours.weekend', 'sr', '"Subota - Nedelja"'::jsonb, true),
('contact.hours.always', 'sr', '"Dostupni 24/7"'::jsonb, true),
('gallery.title', 'sr', '"Galerija"'::jsonb, true),
('gallery.description', 'sr', '"Pogledajte naše predivne apartmane i sadržaje"'::jsonb, true),
('gallery.viewImage', 'sr', '"Pogledaj sliku"'::jsonb, true),
('gallery.enlargedView', 'sr', '"Uvećani prikaz"'::jsonb, true),
('gallery.imageModal', 'sr', '"Pregled slike"'::jsonb, true),
('gallery.noImages.title', 'sr', '"Još uvek nema slika"'::jsonb, true),
('gallery.noImages.message', 'sr', '"Vratite se kasnije kako biste videli ažuriranu galeriju."'::jsonb, true),
('gallery.errors.loadFailed', 'sr', '"Greška pri učitavanju galerije. Molimo pokušajte ponovo kasnije."'::jsonb, true),
('footer.rights', 'sr', '"Sva prava zadržana"'::jsonb, true),
('footer.privacy', 'sr', '"Politika privatnosti"'::jsonb, true),
('footer.terms', 'sr', '"Uslovi korišćenja"'::jsonb, true),
('footer.contactUs', 'sr', '"Kontaktirajte nas"'::jsonb, true),
('footer.followUs', 'sr', '"Pratite nas"'::jsonb, true),
('home.title', 'en', '"Welcome to Jovča Apartments"'::jsonb, true),
ON CONFLICT (key, language) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();
