INSERT INTO content (key, language, value, published) VALUES
('home.title', 'sr', '"Dobrodošli u Apartmane Jovča"'::jsonb, true),
('home.description', 'sr', '"Uživajte u udobnom smeštaju u prelepom okruženju."'::jsonb, true),
('home.subtitle', 'sr', '"Vaš savršeni odmor u srcu prirode"'::jsonb, true),
('home.hero.title', 'sr', '"Doživite udobnost i prirodu"'::jsonb, true),
('home.hero.subtitle', 'sr', '"Rezervišite svoj boravak u modernim apartmanima"'::jsonb, true),
('home.hero.cta', 'sr', '"Rezerviši"'::jsonb, true),
('home.features.title', 'sr', '"Naše prednosti"'::jsonb, true),
('home.features.amenities', 'sr', '"Moderno opremljeni apartmani"'::jsonb, true),
('home.features.location', 'sr', '"Odlična lokacija u blizini atrakcija"'::jsonb, true),
('home.features.parking', 'sr', '"Besplatan parking"'::jsonb, true),
('home.features.wifi', 'sr', '"Besplatan WiFi"'::jsonb, true),
('home.features.breakfast', 'sr', '"Dostupan doručak"'::jsonb, true),
('home.features.petFriendly', 'sr', '"Dozvoljeni ljubimci"'::jsonb, true),
('home.contact.title', 'sr', '"Kontaktirajte nas"'::jsonb, true),
('home.contact.available', 'sr', '"Dostupni smo 24/7 za sve vaše potrebe."'::jsonb, true),
('home.testimonials.title', 'sr', '"Šta kažu naši gosti"'::jsonb, true),
('home.testimonials.readMore', 'sr', '"Pročitaj više recenzija"'::jsonb, true),
('apartments.title', 'sr', '"Naši apartmani"'::jsonb, true),
('apartments.description', 'sr', '"Pronađite savršen smeštaj"'::jsonb, true),
('apartments.amenities', 'sr', '"Sadržaji"'::jsonb, true),
('apartments.size', 'sr', '"Veličina"'::jsonb, true),
('apartments.beds', 'sr', '"Kreveti"'::jsonb, true),
('apartments.capacity', 'sr', '"Kapacitet"'::jsonb, true),
('apartments.viewDetails', 'sr', '"Vidi detalje"'::jsonb, true),
('apartments.bookNow', 'sr', '"Rezerviši"'::jsonb, true),
('apartments.noApartments.title', 'sr', '"Nema dostupnih apartmana"'::jsonb, true),
('apartments.noApartments.message', 'sr', '"Proverite kasnije ili nas kontaktirajte za dostupnost."'::jsonb, true),
('attractions.title', 'sr', '"Lokalne atrakcije"'::jsonb, true),
('attractions.description', 'sr', '"Otkrijte lepotu okolnog područja"'::jsonb, true),
('attractions.readMore', 'sr', '"Pročitaj više"'::jsonb, true),
('attractions.noAttractions.title', 'sr', '"Nema navedenih atrakcija"'::jsonb, true),
('attractions.noAttractions.message', 'sr', '"Proverite kasnije za ažuriranja o lokalnim atrakcijama."'::jsonb, true),
('location.title', 'sr', '"Lokacija"'::jsonb, true),
('location.description', 'sr', '"Kako do nas"'::jsonb, true),
('location.address', 'sr', '"Adresa"'::jsonb, true),
('location.directions', 'sr', '"Uputstva za dolazak"'::jsonb, true),
('location.nearby', 'sr', '"Obližnje atrakcije"'::jsonb, true),
('prices.title', 'sr', '"Cene i Smještaj"'::jsonb, true),
('prices.description', 'sr', '"Transparentne cene bez skrivenih troškova"'::jsonb, true),
('prices.bed', 'sr', '"Tip kreveta"'::jsonb, true),
('prices.capacity', 'sr', '"Kapacitet"'::jsonb, true),
('prices.included', 'sr', '"U cenu je uključeno:"'::jsonb, true),
('prices.perNight', 'sr', '"po noćenju"'::jsonb, true),
('prices.totalPrice', 'sr', '"Ukupna cena"'::jsonb, true),
('prices.selectDates', 'sr', '"Izaberite datume da vidite cene"'::jsonb, true),
('prices.noPrices.title', 'sr', '"Trenutno nema dostupnih cena"'::jsonb, true),
('prices.noPrices.message', 'sr', '"Molimo proverite kasnije ili nas kontaktirajte za više informacija."'::jsonb, true),
('prices.errors.loadFailed', 'sr', '"Greška pri učitavanju cena. Molimo pokušajte ponovo kasnije."'::jsonb, true),
('contact.title', 'sr', '"Kontaktirajte nas"'::jsonb, true),
('contact.description', 'sr', '"Rado ćemo vam odgovoriti"'::jsonb, true),
('contact.form.name', 'sr', '"Vaše ime"'::jsonb, true),
('contact.form.email', 'sr', '"Email adresa"'::jsonb, true),
('contact.form.phone', 'sr', '"Broj telefona"'::jsonb, true),
('contact.form.message', 'sr', '"Vaša poruka"'::jsonb, true),
('contact.form.submit', 'sr', '"Pošalji poruku"'::jsonb, true),
('contact.form.success', 'sr', '"Poruka uspešno poslata! Javićemo vam se uskoro."'::jsonb, true),
('contact.form.error', 'sr', '"Greška pri slanju poruke. Molimo pokušajte ponovo."'::jsonb, true),
('contact.info.title', 'sr', '"Kontakt informacije"'::jsonb, true),
('contact.info.address', 'sr', '"Adresa"'::jsonb, true),
('contact.info.phone', 'sr', '"Telefon"'::jsonb, true),
('contact.info.email', 'sr', '"Email"'::jsonb, true),
('contact.info.whatsapp', 'sr', '"WhatsApp"'::jsonb, true),
('contact.hours.title', 'sr', '"Radno vreme"'::jsonb, true),
('contact.hours.weekdays', 'sr', '"Ponedeljak - Petak"'::jsonb, true),
('contact.hours.weekend', 'sr', '"Subota - Nedelja"'::jsonb, true),
('contact.hours.always', 'sr', '"Dostupni 24/7"'::jsonb, true),
('gallery.title', 'sr', '"Galerija"'::jsonb, true),
('gallery.description', 'sr', '"Pogledajte naše predivne apartmane i sadržaje"'::jsonb, true),
('gallery.viewImage', 'sr', '"Pogledaj sliku"'::jsonb, true),
('gallery.enlargedView', 'sr', '"Uvećani prikaz"'::jsonb, true),
('gallery.imageModal', 'sr', '"Pregled slike"'::jsonb, true),
('gallery.noImages.title', 'sr', '"Još uvek nema slika"'::jsonb, true),
('gallery.noImages.message', 'sr', '"Vratite se kasnije kako biste videli ažuriranu galeriju."'::jsonb, true),
('gallery.errors.loadFailed', 'sr', '"Greška pri učitavanju galerije. Molimo pokušajte ponovo kasnije."'::jsonb, true),
('footer.rights', 'sr', '"Sva prava zadržana"'::jsonb, true),
('footer.privacy', 'sr', '"Politika privatnosti"'::jsonb, true),
('footer.terms', 'sr', '"Uslovi korišćenja"'::jsonb, true),
('footer.contactUs', 'sr', '"Kontaktirajte nas"'::jsonb, true),
('footer.followUs', 'sr', '"Pratite nas"'::jsonb, true),
('home.title', 'en', '"Welcome to Jovča Apartments"'::jsonb, true),
('home.description', 'en', '"Enjoy comfortable accommodation in a beautiful setting."'::jsonb, true),
('home.subtitle', 'en', '"Your perfect getaway in the heart of nature"'::jsonb, true),
('home.hero.title', 'en', '"Experience Comfort & Nature"'::jsonb, true),
('home.hero.subtitle', 'en', '"Book your stay at our modern apartments"'::jsonb, true),
('home.hero.cta', 'en', '"Book Now"'::jsonb, true),
('home.features.title', 'en', '"Our Features"'::jsonb, true),
('home.features.amenities', 'en', '"Modernly equipped apartments"'::jsonb, true),
('home.features.location', 'en', '"Great location near attractions"'::jsonb, true),
('home.features.parking', 'en', '"Free parking"'::jsonb, true),
('home.features.wifi', 'en', '"Free WiFi"'::jsonb, true),
('home.features.breakfast', 'en', '"Breakfast available"'::jsonb, true),
('home.features.petFriendly', 'en', '"Pet friendly"'::jsonb, true),
('home.contact.title', 'en', '"Contact Us"'::jsonb, true),
('home.contact.available', 'en', '"We are available 24/7 for all your needs."'::jsonb, true),
('home.testimonials.title', 'en', '"What Our Guests Say"'::jsonb, true),
('home.testimonials.readMore', 'en', '"Read more reviews"'::jsonb, true),
('apartments.title', 'en', '"Our Apartments"'::jsonb, true),
('apartments.description', 'en', '"Find your perfect accommodation"'::jsonb, true),
('apartments.amenities', 'en', '"Amenities"'::jsonb, true),
('apartments.size', 'en', '"Size"'::jsonb, true),
('apartments.beds', 'en', '"Beds"'::jsonb, true),
('apartments.capacity', 'en', '"Capacity"'::jsonb, true),
('apartments.viewDetails', 'en', '"View Details"'::jsonb, true),
('apartments.bookNow', 'en', '"Book Now"'::jsonb, true),
('apartments.noApartments.title', 'en', '"No apartments available"'::jsonb, true),
('apartments.noApartments.message', 'en', '"Please check back later or contact us for availability."'::jsonb, true),
('attractions.title', 'en', '"Local Attractions"'::jsonb, true),
('attractions.description', 'en', '"Discover the beauty of the surrounding area"'::jsonb, true),
('attractions.readMore', 'en', '"Read more"'::jsonb, true),
('attractions.noAttractions.title', 'en', '"No attractions listed"'::jsonb, true),
('attractions.noAttractions.message', 'en', '"Check back later for updates on local attractions."'::jsonb, true),
('location.title', 'en', '"Location"'::jsonb, true),
('location.description', 'en', '"How to find us"'::jsonb, true),
('location.address', 'en', '"Address"'::jsonb, true),
('location.directions', 'en', '"Get Directions"'::jsonb, true),
('location.nearby', 'en', '"Nearby Attractions"'::jsonb, true),
('prices.title', 'en', '"Prices & Accommodation"'::jsonb, true),
('prices.description', 'en', '"Transparent prices without hidden costs"'::jsonb, true),
('prices.bed', 'en', '"Bed Type"'::jsonb, true),
('prices.capacity', 'en', '"Capacity"'::jsonb, true),
('prices.included', 'en', '"Included in all prices:"'::jsonb, true),
('prices.perNight', 'en', '"per night"'::jsonb, true),
('prices.totalPrice', 'en', '"Total Price"'::jsonb, true),
('prices.selectDates', 'en', '"Select dates to see prices"'::jsonb, true),
('prices.noPrices.title', 'en', '"No pricing information available"'::jsonb, true),
('prices.noPrices.message', 'en', '"Please check back later or contact us for more information."'::jsonb, true),
('prices.errors.loadFailed', 'en', '"Failed to load pricing information. Please try again later."'::jsonb, true),
('contact.title', 'en', '"Contact Us"'::jsonb, true),
('contact.description', 'en', '"We'd love to hear from you"'::jsonb, true),
('contact.form.name', 'en', '"Your Name"'::jsonb, true),
('contact.form.email', 'en', '"Email Address"'::jsonb, true),
('contact.form.phone', 'en', '"Phone Number"'::jsonb, true),
('contact.form.message', 'en', '"Your Message"'::jsonb, true),
('contact.form.submit', 'en', '"Send Message"'::jsonb, true),
('contact.form.success', 'en', '"Message sent successfully! We'll get back to you soon."'::jsonb, true),
('contact.form.error', 'en', '"Failed to send message. Please try again."'::jsonb, true),
('contact.info.title', 'en', '"Contact Information"'::jsonb, true),
('contact.info.address', 'en', '"Address"'::jsonb, true),
('contact.info.phone', 'en', '"Phone"'::jsonb, true),
('contact.info.email', 'en', '"Email"'::jsonb, true),
('contact.info.whatsapp', 'en', '"WhatsApp"'::jsonb, true),
('contact.hours.title', 'en', '"Working Hours"'::jsonb, true),
('contact.hours.weekdays', 'en', '"Monday - Friday"'::jsonb, true),
('contact.hours.weekend', 'en', '"Saturday - Sunday"'::jsonb, true),
('contact.hours.always', 'en', '"Available 24/7"'::jsonb, true),
('gallery.title', 'en', '"Gallery"'::jsonb, true),
('gallery.description', 'en', '"View our beautiful apartments and facilities"'::jsonb, true),
('gallery.viewImage', 'en', '"View image"'::jsonb, true),
('gallery.enlargedView', 'en', '"Enlarged view"'::jsonb, true),
('gallery.imageModal', 'en', '"Image preview"'::jsonb, true),
('gallery.noImages.title', 'en', '"No images yet"'::jsonb, true),
('gallery.noImages.message', 'en', '"Check back later for updates to our gallery."'::jsonb, true),
('gallery.errors.loadFailed', 'en', '"Failed to load gallery. Please try again later."'::jsonb, true),
('footer.rights', 'en', '"All rights reserved"'::jsonb, true),
('footer.privacy', 'en', '"Privacy Policy"'::jsonb, true),
('footer.terms', 'en', '"Terms of Service"'::jsonb, true),
('footer.contactUs', 'en', '"Contact Us"'::jsonb, true),
('footer.followUs', 'en', '"Follow Us"'::jsonb, true),
('home.title', 'de', '"Willkommen in den Apartments Jovča"'::jsonb, true),
('home.description', 'de', '"Genießen Sie komfortable Unterkunft im Herzen der Natur."'::jsonb, true),
('home.subtitle', 'de', '"Ihr perfekter Urlaub im Herzen der Natur"'::jsonb, true),
('home.hero.title', 'de', '"Erleben Sie Komfort & Natur"'::jsonb, true),
('home.hero.subtitle', 'de', '"Buchen Sie Ihren Aufenthalt in unseren modernen Apartments"'::jsonb, true),
('home.hero.cta', 'de', '"Jetzt buchen"'::jsonb, true),
('home.features.title', 'de', '"Unsere Merkmale"'::jsonb, true),
('home.features.amenities', 'de', '"Modern eingerichtete Apartments"'::jsonb, true),
('home.features.location', 'de', '"Großartige Lage nahe Attraktionen"'::jsonb, true),
('home.features.parking', 'de', '"Kostenloser Parkplatz"'::jsonb, true),
('home.features.wifi', 'de', '"Kostenloses WLAN"'::jsonb, true),
('home.features.breakfast', 'de', '"Frühstück verfügbar"'::jsonb, true),
('home.features.petFriendly', 'de', '"Haustiere willkommen"'::jsonb, true),
('home.contact.title', 'de', '"Kontaktieren Sie uns"'::jsonb, true),
('home.contact.available', 'de', '"Wir sind 24/7 für alle Ihre Bedürfnisse verfügbar."'::jsonb, true),
('home.testimonials.title', 'de', '"Was unsere Gäste sagen"'::jsonb, true),
('home.testimonials.readMore', 'de', '"Weitere Bewertungen lesen"'::jsonb, true),
('apartments.title', 'de', '"Unsere Apartments"'::jsonb, true),
('apartments.description', 'de', '"Finden Sie Ihre perfekte Unterkunft"'::jsonb, true),
('apartments.amenities', 'de', '"Ausstattung"'::jsonb, true),
('apartments.size', 'de', '"Größe"'::jsonb, true),
('apartments.beds', 'de', '"Betten"'::jsonb, true),
('apartments.capacity', 'de', '"Kapazität"'::jsonb, true),
('apartments.viewDetails', 'de', '"Details ansehen"'::jsonb, true),
('apartments.bookNow', 'de', '"Jetzt buchen"'::jsonb, true),
('apartments.noApartments.title', 'de', '"Keine Apartments verfügbar"'::jsonb, true),
('apartments.noApartments.message', 'de', '"Bitte schauen Sie später vorbei oder kontaktieren Sie uns für Verfügbarkeit."'::jsonb, true),
('attractions.title', 'de', '"Lokale Sehenswürdigkeiten"'::jsonb, true),
('attractions.description', 'de', '"Entdecken Sie die Schönheit der Umgebung"'::jsonb, true),
('attractions.readMore', 'de', '"Mehr lesen"'::jsonb, true),
('attractions.noAttractions.title', 'de', '"Keine Sehenswürdigkeiten gelistet"'::jsonb, true),
('attractions.noAttractions.message', 'de', '"Schauen Sie später für Updates zu lokalen Sehenswürdigkeiten vorbei."'::jsonb, true),
('location.title', 'de', '"Lage"'::jsonb, true),
('location.description', 'de', '"So finden Sie uns"'::jsonb, true),
('location.address', 'de', '"Adresse"'::jsonb, true),
('location.directions', 'de', '"Wegbeschreibung"'::jsonb, true),
('location.nearby', 'de', '"Nahegelegene Sehenswürdigkeiten"'::jsonb, true),
('prices.title', 'de', '"Preise und Unterkunft"'::jsonb, true),
('prices.description', 'de', '"Transparente Preise ohne versteckte Kosten"'::jsonb, true),
('prices.bed', 'de', '"Betttyp"'::jsonb, true),
('prices.capacity', 'de', '"Kapazität"'::jsonb, true),
('prices.included', 'de', '"In allen Preisen enthalten:"'::jsonb, true),
('prices.perNight', 'de', '"pro Nacht"'::jsonb, true),
('prices.totalPrice', 'de', '"Gesamtpreis"'::jsonb, true),
('prices.selectDates', 'de', '"Wählen Sie Daten, um Preise zu sehen"'::jsonb, true),
('prices.noPrices.title', 'de', '"Keine Preisinformationen verfügbar"'::jsonb, true),
('prices.noPrices.message', 'de', '"Bitte schauen Sie später vorbei oder kontaktieren Sie uns für weitere Informationen."'::jsonb, true),
('prices.errors.loadFailed', 'de', '"Preisinformationen konnten nicht geladen werden. Bitte versuchen Sie es später erneut."'::jsonb, true),
('contact.title', 'de', '"Kontaktieren Sie uns"'::jsonb, true),
('contact.description', 'de', '"Wir freuen uns von Ihnen zu hören"'::jsonb, true),
('contact.form.name', 'de', '"Ihr Name"'::jsonb, true),
('contact.form.email', 'de', '"E-Mail-Adresse"'::jsonb, true),
('contact.form.phone', 'de', '"Telefonnummer"'::jsonb, true),
('contact.form.message', 'de', '"Ihre Nachricht"'::jsonb, true),
('contact.form.submit', 'de', '"Nachricht senden"'::jsonb, true),
('contact.form.success', 'de', '"Nachricht erfolgreich gesendet! Wir melden uns bald bei Ihnen."'::jsonb, true),
('contact.form.error', 'de', '"Fehler beim Senden der Nachricht. Bitte versuchen Sie es erneut."'::jsonb, true),
('contact.info.title', 'de', '"Kontaktinformationen"'::jsonb, true),
('contact.info.address', 'de', '"Adresse"'::jsonb, true),
('contact.info.phone', 'de', '"Telefon"'::jsonb, true),
('contact.info.email', 'de', '"E-Mail"'::jsonb, true),
('contact.info.whatsapp', 'de', '"WhatsApp"'::jsonb, true),
('contact.hours.title', 'de', '"Öffnungszeiten"'::jsonb, true),
('contact.hours.weekdays', 'de', '"Montag - Freitag"'::jsonb, true),
('contact.hours.weekend', 'de', '"Samstag - Sonntag"'::jsonb, true),
('contact.hours.always', 'de', '"24/7 verfügbar"'::jsonb, true),
('gallery.title', 'de', '"Galerie"'::jsonb, true),
('gallery.description', 'de', '"Sehen Sie sich unsere schönen Apartments und Einrichtungen an"'::jsonb, true),
('gallery.viewImage', 'de', '"Bild ansehen"'::jsonb, true),
('gallery.enlargedView', 'de', '"Vergrößerte Ansicht"'::jsonb, true),
('gallery.imageModal', 'de', '"Bildvorschau"'::jsonb, true),
('gallery.noImages.title', 'de', '"Noch keine Bilder"'::jsonb, true),
('gallery.noImages.message', 'de', '"Schauen Sie später für Updates in unserer Galerie vorbei."'::jsonb, true),
('gallery.errors.loadFailed', 'de', '"Galerie konnte nicht geladen werden. Bitte versuchen Sie es später erneut."'::jsonb, true),
('footer.rights', 'de', '"Alle Rechte vorbehalten"'::jsonb, true),
('footer.privacy', 'de', '"Datenschutz"'::jsonb, true),
('footer.terms', 'de', '"Nutzungsbedingungen"'::jsonb, true),
('footer.contactUs', 'de', '"Kontaktieren Sie uns"'::jsonb, true),
('footer.followUs', 'de', '"Folgen Sie uns"'::jsonb, true),
('home.title', 'it', '"Benvenuti negli Appartamenti Jovča"'::jsonb, true),
('home.description', 'it', '"Goditi un soggiorno confortevole nel cuore della natura."'::jsonb, true),
('home.subtitle', 'it', '"La tua perfetta fuga nel cuore della natura"'::jsonb, true),
('home.hero.title', 'it', '"Vivi Comfort e Natura"'::jsonb, true),
('home.hero.subtitle', 'it', '"Prenota il tuo soggiorno nei nostri appartamenti moderni"'::jsonb, true),
('home.hero.cta', 'it', '"Prenota ora"'::jsonb, true),
('home.features.title', 'it', '"Le nostre caratteristiche"'::jsonb, true),
('home.features.amenities', 'it', '"Appartamenti arredati modernamente"'::jsonb, true),
('home.features.location', 'it', '"Ottima posizione vicino alle attrazioni"'::jsonb, true),
('home.features.parking', 'it', '"Parcheggio gratuito"'::jsonb, true),
('home.features.wifi', 'it', '"WiFi gratuito"'::jsonb, true),
('home.features.breakfast', 'it', '"Colazione disponibile"'::jsonb, true),
('home.features.petFriendly', 'it', '"Animali ammessi"'::jsonb, true),
('home.contact.title', 'it', '"Contattaci"'::jsonb, true),
('home.contact.available', 'it', '"Siamo disponibili 24/7 per tutte le tue esigenze."'::jsonb, true),
('home.testimonials.title', 'it', '"Cosa dicono i nostri ospiti"'::jsonb, true),
('home.testimonials.readMore', 'it', '"Leggi altre recensioni"'::jsonb, true),
('apartments.title', 'it', '"I nostri appartamenti"'::jsonb, true),
('apartments.description', 'it', '"Trova la tua sistemazione perfetta"'::jsonb, true),
('apartments.amenities', 'it', '"Servizi"'::jsonb, true),
('apartments.size', 'it', '"Dimensione"'::jsonb, true),
('apartments.beds', 'it', '"Letti"'::jsonb, true),
('apartments.capacity', 'it', '"Capacità"'::jsonb, true),
('apartments.viewDetails', 'it', '"Vedi dettagli"'::jsonb, true),
('apartments.bookNow', 'it', '"Prenota ora"'::jsonb, true),
('apartments.noApartments.title', 'it', '"Nessun appartamento disponibile"'::jsonb, true),
('apartments.noApartments.message', 'it', '"Controlla più tardi o contattaci per la disponibilità."'::jsonb, true),
('attractions.title', 'it', '"Attrazioni locali"'::jsonb, true),
('attractions.description', 'it', '"Scopri la bellezza della zona circostante"'::jsonb, true),
('attractions.readMore', 'it', '"Leggi di più"'::jsonb, true),
('attractions.noAttractions.title', 'it', '"Nessuna attrazione elencata"'::jsonb, true),
('attractions.noAttractions.message', 'it', '"Controlla più tardi per aggiornamenti sulle attrazioni locali."'::jsonb, true),
('location.title', 'it', '"Posizione"'::jsonb, true),
('location.description', 'it', '"Come trovarci"'::jsonb, true),
('location.address', 'it', '"Indirizzo"'::jsonb, true),
('location.directions', 'it', '"Ottieni indicazioni"'::jsonb, true),
('location.nearby', 'it', '"Attrazioni vicine"'::jsonb, true),
('prices.title', 'it', '"Prezzi e Sistemazioni"'::jsonb, true),
('prices.description', 'it', '"Prezzi trasparenti senza costi nascosti"'::jsonb, true),
('prices.bed', 'it', '"Tipo di letto"'::jsonb, true),
('prices.capacity', 'it', '"Capacità"'::jsonb, true),
('prices.included', 'it', '"Incluso in tutti i prezzi:"'::jsonb, true),
('prices.perNight', 'it', '"a notte"'::jsonb, true),
('prices.totalPrice', 'it', '"Prezzo totale"'::jsonb, true),
('prices.selectDates', 'it', '"Seleziona le date per vedere i prezzi"'::jsonb, true),
('prices.noPrices.title', 'it', '"Nessuna informazione sui prezzi disponibile"'::jsonb, true),
('prices.noPrices.message', 'it', '"Controlla più tardi o contattaci per ulteriori informazioni."'::jsonb, true),
('prices.errors.loadFailed', 'it', '"Impossibile caricare le informazioni sui prezzi. Riprova più tardi."'::jsonb, true),
('contact.title', 'it', '"Contattaci"'::jsonb, true),
('contact.description', 'it', '"Ci piacerebbe sentire da te"'::jsonb, true),
('contact.form.name', 'it', '"Il tuo nome"'::jsonb, true),
('contact.form.email', 'it', '"Indirizzo email"'::jsonb, true),
('contact.form.phone', 'it', '"Numero di telefono"'::jsonb, true),
('contact.form.message', 'it', '"Il tuo messaggio"'::jsonb, true),
('contact.form.submit', 'it', '"Invia messaggio"'::jsonb, true),
('contact.form.success', 'it', '"Messaggio inviato con successo! Ti risponderemo presto."'::jsonb, true),
('contact.form.error', 'it', '"Errore nell'invio del messaggio. Riprova."'::jsonb, true),
('contact.info.title', 'it', '"Informazioni di contatto"'::jsonb, true),
('contact.info.address', 'it', '"Indirizzo"'::jsonb, true),
('contact.info.phone', 'it', '"Telefono"'::jsonb, true),
('contact.info.email', 'it', '"Email"'::jsonb, true),
('contact.info.whatsapp', 'it', '"WhatsApp"'::jsonb, true),
('contact.hours.title', 'it', '"Orari di lavoro"'::jsonb, true),
('contact.hours.weekdays', 'it', '"Lunedì - Venerdì"'::jsonb, true),
('contact.hours.weekend', 'it', '"Sabato - Domenica"'::jsonb, true),
('contact.hours.always', 'it', '"Disponibile 24/7"'::jsonb, true),
('gallery.title', 'it', '"Galleria"'::jsonb, true),
('gallery.description', 'it', '"Visualizza i nostri bellissimi appartamenti e strutture"'::jsonb, true),
('gallery.viewImage', 'it', '"Visualizza immagine"'::jsonb, true),
('gallery.enlargedView', 'it', '"Vista ingrandita"'::jsonb, true),
('gallery.imageModal', 'it', '"Anteprima immagine"'::jsonb, true),
('gallery.noImages.title', 'it', '"Nessuna immagine ancora"'::jsonb, true),
('gallery.noImages.message', 'it', '"Controlla più tardi per aggiornamenti alla nostra galleria."'::jsonb, true),
('gallery.errors.loadFailed', 'it', '"Impossibile caricare la galleria. Riprova più tardi."'::jsonb, true),
('footer.rights', 'it', '"Tutti i diritti riservati"'::jsonb, true),
('footer.privacy', 'it', '"Informativa sulla privacy"'::jsonb, true),
('footer.terms', 'it', '"Termini di servizio"'::jsonb, true),
('footer.contactUs', 'it', '"Contattaci"'::jsonb, true),
('footer.followUs', 'it', '"Seguici"'::jsonb, true)
ON CONFLICT (key, language) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();