-- Add 3 more sample apartments for testing
-- These are temporary data that can be edited later through Admin Panel

-- Apartment 2: Standard
INSERT INTO apartments (
  slug,
  name,
  description,
  bed_type,
  capacity,
  base_price_eur,
  status,
  display_order,
  size_sqm,
  bathroom_count,
  balcony,
  check_in_time,
  check_out_time,
  min_stay_nights,
  max_stay_nights,
  weekend_price_eur,
  weekly_discount_percent,
  monthly_discount_percent,
  selected_amenities,
  selected_rules,
  selected_view,
  images,
  city,
  country,
  latitude,
  longitude
) VALUES (
  'apartman-standard',
  '{"sr": "Apartman Standard", "en": "Standard Apartment", "de": "Standard Apartment", "it": "Appartamento Standard"}',
  '{"sr": "Komforan apartman sa svim potrebnim sadržajima za ugodan boravak. Idealan za parove ili manje porodice.", "en": "Comfortable apartment with all necessary amenities for a pleasant stay. Ideal for couples or small families.", "de": "Komfortables Apartment mit allen notwendigen Annehmlichkeiten für einen angenehmen Aufenthalt.", "it": "Appartamento confortevole con tutti i comfort necessari per un soggiorno piacevole."}',
  '{"sr": "Bračni krevet", "en": "Double Bed", "de": "Doppelbett", "it": "Letto Matrimoniale"}',
  3,
  35,
  'active',
  2,
  40,
  1,
  true,
  '14:00',
  '10:00',
  2,
  0,
  40,
  10,
  15,
  ARRAY['wifi', 'parking', 'ac', 'tv', 'kitchen'],
  ARRAY['no_smoking', 'quiet_hours_22'],
  'lake_view',
  '["https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=800&q=80", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80"]',
  'Herceg Novi',
  'Crna Gora',
  42.4511,
  18.5311
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  updated_at = NOW();

-- Apartment 3: Family
INSERT INTO apartments (
  slug,
  name,
  description,
  bed_type,
  capacity,
  base_price_eur,
  status,
  display_order,
  size_sqm,
  bathroom_count,
  balcony,
  check_in_time,
  check_out_time,
  min_stay_nights,
  max_stay_nights,
  weekend_price_eur,
  weekly_discount_percent,
  monthly_discount_percent,
  selected_amenities,
  selected_rules,
  selected_view,
  images,
  city,
  country,
  latitude,
  longitude
) VALUES (
  'apartman-family',
  '{"sr": "Apartman Family", "en": "Family Apartment", "de": "Familien Apartment", "it": "Appartamento Familiare"}',
  '{"sr": "Prostran apartman idealan za porodice, sa dve spavaće sobe i velikim dnevnim boravkom. Potpuno opremljen za udoban porodični odmor.", "en": "Spacious apartment ideal for families, with two bedrooms and a large living room. Fully equipped for a comfortable family vacation.", "de": "Geräumiges Apartment ideal für Familien, mit zwei Schlafzimmern und einem großen Wohnzimmer.", "it": "Appartamento spazioso ideale per famiglie, con due camere da letto e un ampio soggiorno."}',
  '{"sr": "2 Bračna kreveta", "en": "2 Double Beds", "de": "2 Doppelbetten", "it": "2 Letti Matrimoniali"}',
  6,
  50,
  'active',
  3,
  65,
  2,
  true,
  '14:00',
  '10:00',
  3,
  0,
  60,
  15,
  20,
  ARRAY['wifi', 'parking', 'ac', 'tv', 'kitchen'],
  ARRAY['no_smoking', 'pets_allowed', 'quiet_hours_22'],
  'lake_view',
  '["https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80"]',
  'Herceg Novi',
  'Crna Gora',
  42.4515,
  18.5315
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  updated_at = NOW();

-- Apartment 4: Studio
INSERT INTO apartments (
  slug,
  name,
  description,
  bed_type,
  capacity,
  base_price_eur,
  status,
  display_order,
  size_sqm,
  bathroom_count,
  balcony,
  check_in_time,
  check_out_time,
  min_stay_nights,
  max_stay_nights,
  weekend_price_eur,
  weekly_discount_percent,
  monthly_discount_percent,
  selected_amenities,
  selected_rules,
  selected_view,
  images,
  city,
  country,
  latitude,
  longitude
) VALUES (
  'apartman-studio',
  '{"sr": "Apartman Studio", "en": "Studio Apartment", "de": "Studio Apartment", "it": "Monolocale"}',
  '{"sr": "Kompaktan studio apartman, savršen za parove ili solo putnike. Moderan dizajn sa svim potrebnim sadržajima.", "en": "Compact studio apartment, perfect for couples or solo travelers. Modern design with all necessary amenities.", "de": "Kompaktes Studio-Apartment, perfekt für Paare oder Alleinreisende.", "it": "Monolocale compatto, perfetto per coppie o viaggiatori singoli."}',
  '{"sr": "Francuski ležaj", "en": "Queen Bed", "de": "Französisches Bett", "it": "Letto alla Francese"}',
  2,
  30,
  'active',
  4,
  30,
  1,
  true,
  '14:00',
  '10:00',
  1,
  0,
  35,
  10,
  15,
  ARRAY['wifi', 'parking', 'ac', 'tv', 'kitchen'],
  ARRAY['no_smoking', 'quiet_hours_22'],
  'mountain_view',
  '["https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80", "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80"]',
  'Herceg Novi',
  'Crna Gora',
  42.4508,
  18.5308
) ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  updated_at = NOW();

-- Update display_order for existing apartment if it exists
UPDATE apartments 
SET display_order = 1 
WHERE slug = 'apartman-veliki' OR slug = 'deluxe-apartment';

COMMENT ON TABLE apartments IS 'All apartment data is now in the database. Edit through Admin Panel at /admin';
