-- 2026-06-18 — Apartman opisi (description) prepisani u tonu „vikendica na obali Bovanskog jezera"
-- Scope: SAMO `description` jsonb (sr/en/de/it). Nazivi i strukturna polja NEDIRANI.
-- Ton: priroda/jezero/mir, iskren, BEZ „luksuz". Pogled: apt-1,2 jezero; apt-3,4 planina.
-- Primena: Supabase SQL editor (paste) ILI `supabase db push`. Reverzibilno (stari description je u git istoriji DB-a / backupu).

-- apartman-1 — Studio, pogled na jezero
UPDATE public.apartments SET description = jsonb_build_object(
  'sr', $d$Na samoj obali Bovanskog jezera, svega dvadesetak metara od vode. Studio je prisno i toplo sređen — za one koji su došli zbog jezera, a ne zbog sobe. Jutro uz kafu s pogledom na mirnu površinu, popodne na vodi, veče uz roštilj. Sve što treba je tu, bez viška. Za par ili putnika samca koji zna zašto je u prirodi.$d$,
  'en', $d$Right on the shore of Bovan Lake, just steps from the water. This studio is cozy and unpretentious, put together with care — for those who came for the lake, not the room. Morning coffee with a view of the still water, afternoons on the lake, evenings around the grill. Everything you need is here, nothing more. For a couple or a solo traveler who knows exactly why they came to nature.$d$,
  'de', $d$Direkt am Ufer des Bovan-Sees — nur ein Steinwurf vom Wasser entfernt. Das Studio ist heimelig und herzlich eingerichtet: für alle, die wegen des Sees hier sind, nicht wegen des Zimmers. Morgenkaffee mit Blick auf die stille Wasseroberfläche, nachmittags am See, abends am Grill. Alles, was man braucht, ist da — nichts mehr, nichts weniger. Für Paare oder Alleinreisende, die wissen, warum sie in der Natur sind.$d$,
  'it', $d$Sulla riva stessa del Lago di Bovan, a una ventina di metri dall'acqua. Uno studio accogliente e ben curato — per chi è venuto per il lago, non per la stanza. Caffè la mattina con vista sulla superficie calma, pomeriggio sull'acqua, sera intorno al barbecue. Tutto quello che serve c'è, nient'altro. Per una coppia o un viaggiatore solitario che sa perché è in mezzo alla natura.$d$
), updated_at = now() WHERE slug = 'apartman-1';

-- apartman-2 — Deluxe, pogled na jezero, terasa
UPDATE public.apartments SET description = jsonb_build_object(
  'sr', $d$Prostraniji smeštaj na samoj obali Bovanskog jezera, sa terasom okrenutom prema vodi. Jutarnja kafa dok se jezero budi, zvuk talasića, svežina borove šume — to je ono što ovaj apartman nudi. Uredno sređen i dobro opremljen za boravak u prirodi: ne kao gradska destinacija, nego kao pravi odmor. Za one kojima malo više prostora i mirna terasa uz jezero znače sve.$d$,
  'en', $d$A more spacious place right on the shore of Bovan Lake, with a terrace facing the water. Morning coffee as the lake wakes up, the quiet ripple of waves, the freshness of pine air — that's what this place offers. Neat and well-equipped for a stay in nature: not a city getaway, but a proper rest. For those who value a bit more room and a calm terrace by the water above all else.$d$,
  'de', $d$Geräumigere Unterkunft direkt am Ufer des Bovan-Sees, mit einer Terrasse zum Wasser hin. Der Morgenkaffee, während der See erwacht, das leise Plätschern der Wellen, die frische Luft des Kiefernwaldes — das ist es, was dieser Ort zu bieten hat. Ordentlich eingerichtet und gut ausgestattet für einen Aufenthalt in der Natur: kein Stadthotel, sondern echter Urlaub. Für alle, denen etwas mehr Platz und eine ruhige Terrasse am Wasser alles bedeuten.$d$,
  'it', $d$Sistemazione più spaziosa sulla riva del Lago di Bovan, con terrazza affacciata sull'acqua. Il caffè del mattino mentre il lago si sveglia, il suono delle piccole onde, la frescura del bosco di pini — è questo che offre. Ben tenuta e ben attrezzata per un soggiorno nella natura: non una meta cittadina, ma un vero riposo. Per chi cerca qualche metro in più e una terrazza tranquilla a bordo lago.$d$
), updated_at = now() WHERE slug = 'apartman-2';

-- apartman-3 — Standard, pogled na planinu/prirodu
UPDATE public.apartments SET description = jsonb_build_object(
  'sr', $d$Udoban smeštaj u vikendici na obali Bovanskog jezera, s pogledom na zelenilo i okolnu planinu. Soba je jednostavna, čista i prijatna — sređena baš onako koliko je potrebno za boravak gde priroda preuzima ulogu glavnog domaćina. Jezero je peške, šetnje su odmah za uglom, vazduh je drukčiji od gradskog. Za goste koji traže mir i ničeg drugog.$d$,
  'en', $d$A comfortable room in a lakeside cottage on Bovan Lake, with views of the greenery and the surrounding mountain. Simple, clean, and pleasant — set up exactly as much as you need for a stay where nature does most of the work. The lake is a short walk away, trails start right outside, and the air is nothing like the city's. For guests who came for quiet, and nothing else.$d$,
  'de', $d$Gemütliche Unterkunft in einem Ferienhaus am Ufer des Bovan-Sees, mit Blick ins Grüne und auf die umliegenden Berge. Das Zimmer ist schlicht, sauber und angenehm — so eingerichtet, wie es eben sein muss, wenn die Natur die Hauptrolle übernimmt. Der See ist zu Fuß erreichbar, Wanderwege beginnen gleich um die Ecke, die Luft ist eine andere als in der Stadt. Für Gäste, die Ruhe suchen — und nichts weiter.$d$,
  'it', $d$Sistemazione confortevole in una casa di villeggiatura sulla riva del Lago di Bovan, con vista sul verde e sulla montagna circostante. La stanza è semplice, pulita e piacevole — curata esattamente quanto basta per un soggiorno dove la natura fa da padrona di casa. Il lago è a pochi passi, i sentieri sono dietro l'angolo, l'aria è diversa da quella di città. Per gli ospiti che cercano la pace e nient'altro.$d$
), updated_at = now() WHERE slug = 'apartman-3';

-- apartman-4 — Porodični, pogled na planinu/prirodu
UPDATE public.apartments SET description = jsonb_build_object(
  'sr', $d$Prostraniji apartman za društvo ili porodicu — u vikendici na samoj obali Bovanskog jezera. Pogled ide prema planini i okolnoj šumi, a voda je tik do vas. Ima mesta za sve: za ručak u hladu, za roštilj, za ribolov zorom, za kupanje u podne. Sređeno lepo i funkcionalno, bez pretenzija. Dobar odmor ne traži mnogo — traži pravo mesto, a ovo to je.$d$,
  'en', $d$A larger apartment for a group or a family — in a cottage right on the shore of Bovan Lake. The view stretches toward the mountain and the surrounding forest, and the water is just outside. There's room for everything: a shaded lunch, an evening at the grill, early-morning fishing, an afternoon swim. Done up nicely and practically, without pretense. A good rest doesn't ask for much — just the right place, and this is it.$d$,
  'de', $d$Geräumigere Unterkunft für Gruppen oder Familien — in einem Ferienhaus direkt am Ufer des Bovan-Sees. Der Blick geht zur Berglandschaft und in den umliegenden Wald, das Wasser ist zum Greifen nah. Es ist Platz für alle: für ein Mittagessen im Schatten, für den Grillabend, für Angeln in der Morgendämmerung, für ein Bad zu Mittag. Schön und funktional eingerichtet, ohne Ansprüche. Ein guter Urlaub braucht nicht viel — er braucht den richtigen Ort. Und den findet man genau hier.$d$,
  'it', $d$Sistemazione più ampia, ideale per un gruppo o una famiglia — in una casa di villeggiatura sulla riva stessa del Lago di Bovan. La vista spazia verso la montagna e il bosco circostante, mentre l'acqua è a due passi. C'è spazio per tutti: per il pranzo all'ombra, il barbecue, la pesca all'alba, il bagno a mezzogiorno. Curata con gusto e funzionale, senza pretese. Una bella vacanza non chiede molto — chiede il posto giusto, ed è questo.$d$
), updated_at = now() WHERE slug = 'apartman-4';
